### ISSUE TITLE
DBus Backend error

### ISSUE THREAD

**Issue by lphabc** [JonMagon/KDiskMark#102]
- Linux-distro (kernel version): 7.9
- Desktop Environment (KDE/GNOME etc.): Gnome
- Qt Version: qt5-qtbase-5.9.7-5.el7_9.x86_64
- KDiskMark Version: 2.2.1
- FIO Version: fio-3.7.2

### Description: Decided to try an older version as they are so many packages to add with trying to 3.1.1 working. 2.2.1 is much easier to build on rhel 7. It builds and installs fine but after selecting the file location and starting a test it comes back with:
DBus Backend error: service start org.jonmagon.kdiskmark failed: Launch helper exited with unknown return code 255.

I've tried this on more that one system but always the same result.

Sep 27 05:49:01 temp-7-57.dev.tne dbus[954]: [system] Activating service name='org.jonmagon.kdiskmark' (using servicehelper)
Sep 27 05:49:01 temp-7-57.dev.tne org.jonmagon.kdiskmark[22181]: Error registering helper DBus service "org.jonmagon.kdiskmark" "Connection \":1.508\" is not allowed to own the service \"org.jonmagon.kdiskmark\" due to security policies in the configuration file"

Sep 27 05:49:01 temp-7-57.dev.tne org.jonmagon.kdiskmark[22181]: Helper initialization failed
Sep 27 05:49:01 temp-7-57.dev.tne dbus[954]: [system] Activated service 'org.jonmagon.kdiskmark' failed: Launch helper exited with unknown return code 255

**Comment by JonMagon** [comment]
It looks like a local problem with the Dbus service. However, that older versions are not supported. There are binary rpm packages available in the releases, maybe you will use them?
