### ISSUE TITLE
Running the app as regular user outputs wrong read speeds

### ISSUE THREAD

**Issue by raspin0** [JonMagon/KDiskMark#103]
- Linux-distro (kernel version): Deepin 20.7.1 x86_64 5.18.17-amd64-desktop-hwe
- Desktop Environment (KDE/GNOME etc.): Deepin
- Qt Version: -
- KDiskMark Version: 3.1.2
- FIO Version: fio-3.32

### Description:

Flatpak & Appimage (NO ROOT ACCESS)
![Zrzut ekranu_kdiskmark_20221025173734](https://user-images.githubusercontent.com/39202451/197822559-5a3e881f-d694-43c8-9b0a-bf9348a5b717.png)

Appimage (RUNNING AS ROOT) - Correct results (Compared against other benchmarks of this pendrive)
Command: `sudo env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY ./KDiskMark-3.1.2-fio-3.32-x86_64.AppImage`

![Zrzut ekranu_kdiskmark_20221025175054](https://user-images.githubusercontent.com/39202451/197822564-b653f602-242f-4378-92e8-2603b5bc9d5b.png)

**Comment by JonMagon** [comment]
That's why a special warning is displayed at the top right.

**Comment by raspin0** [comment]
The warning does not inform you that the readings will be incorrect, nor it doesn't specify that root access is required to perform a proper benchmark. If the application doesn't work on Flatpak and Appimage and there is no desire to fix issues why builds of this application are available on those platforms?

**Comment by JonMagon** [comment]
It does. Whether it is right or wrong depends on the device and the mounting arguments.

**Comment by raspin0** [comment]
![obraz](https://user-images.githubusercontent.com/39202451/197842384-24314dce-889d-46c6-ab08-467faeeb8c6d.png)
Where does it say that the application may produce incorrect results? I don't think the app should launch at all if there are such known problems.

**Comment by JonMagon** [comment]
Right at the beginning.

**Comment by raspin0** [comment]
That's not true, limited functionality doesn't mean or even imply that the application may produce incorrect results.

**Comment by raspin0** [comment]
I guess there's no point in arguing like that, so I will just leave my final opinion.

Running KdiskMark in usermode as a Flatpak and Appimage is flawed and it's known to produce incorrect values, hence unless there's a will to fix the issues, it should be forbidden to run without root and removed from platforms where it doesn't work correctly. Any kind of warning, even a bigger one is not enough. One of the core principles of such tools is reliability and without strong focus on quality of produced results I personally can’t recommend this application to anyone.

**Comment by JonMagon** [comment]
I say it again: everything works as expected.
If the caching distorts the result, the user needs to run the portable app as a super user to be able to bypass it.
Running the GUI as root user is not the best practice, but the only possible one in this case.
Moreover, it is usually the internal devices that are tested. Or right configured external ones.

Whether or not to recommend it is your decision. Flatpak and AppImage packages are successfully used by many people.
I'm not going to limit the ways of delivery, or to force the user to run _an app from the Internet_ as sudo.
The warning in the upper right corner is sufficient.

**Comment by JonMagon** [comment]
Ok, I will expand on the warning text.

**Comment by raspin0** [comment]
Thank you for understanding. That is a very good idea. I'd think about ways of actually fixing this issue or if it's unfixable just making sure there's no way a user can get an incorrect values. Even if the user skips all the warnings there should be a system in place that prevents incorrect values from ever appearing.

Ultimately though, imo. it's unacceptable to have an app that half works dependingly on where and how you turn it on.

Good Luck :)
