### ISSUE TITLE
Feature Request: Support for Debian

### ISSUE THREAD

**Issue by Danny3** [JonMagon/KDiskMark#110]
Hello!

I just discovered this and it seems to work great on Debian 12 with latest KDE Plasma.

KDiskMark version: 3.1.2
FIO version: 3.33

But the installation was not that easy.
Since Debian didn't seem to be supported, I figured out the easiest and fastest way to try it would be the AppImage version.
But after trying to run it it complained, about some FIO, which I didn't know what it meant at the time.
So I downloaded then the .deb version and tried to install it with the normal:
sudo dpkg -i package.deb, which gave an error about missing fio dependence that could not be installed for some reason.

I installed that manually and then installed this program again, which installed correctly this time.
This happened on Debian 12 that I'm currently testing and works pretty much ok with every program I'm using.

Since Debian comes with about 50K packages and it's the parent of Ubuntu and its flavors I think it would be great to see this program on this list:
https://people.debian.org/~eriberto/udd/top_500_new.html
And to be able to install it easily and fast with the normal "sudo apt install kdiskmark" command.

Do you think it's possible to publish it also in Debian's repository?

Thank you very much!

**Comment by JonMagon** [comment]
I created the request over two years ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973684
Given that [many packages have been in this state for many years](https://www.debian.org/devel/wnpp/being_packaged.html), I think this could be resolved in 2030.

**Comment by Danny3** [comment]
> I created the request over two years ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973684 Given that [many packages have been in this state for many years](https://www.debian.org/devel/wnpp/being_packaged.html), I think this could be resolved in 2030.

OMG, this is very bad!

I mean, when I created this issue I didn't expected that a request has already been done and 2 years have passed, without being approved.

Especially since this is such a small program (I assume) and that it depends on Flexible I/O Tester, which is already there and because it works great.

And at least for me on Debian 12 and KDE Plasma looks great, as a native program would and also works very well, without any problems.

Thank you very much for creating this wonderful program that works so well and for alredy making a request to be included in Debian's repository!

Hopefully we'll have some success with that sooner than later.

**Comment by Tachi107** [comment]
> I created the request over two years ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973684
> Given that [many packages have been in this state for many years](https://www.debian.org/devel/wnpp/being_packaged.html), I think this could be resolved in 2030.

Hi, thanks for your interest in Debian! Unfortunately, simply opening an ITP bug doesn't magically make the package available in the archive, the process is a bit more involved.

After opening the ITP (Intent To Package), you should publish your package on mentors.debian.net, a site where Debian Developers can review contributors' work and eventually upload the package in the archive, acting like a "sponsor" or "mentor".

Feel free to ask me anything if you have any doubt, I'll be happy to help :)

(I'm not a DD (Debian Developer) myself, I'm a DM (Debian Maintainer), meaning that I can only push updates to packages I already maintain, but cannot publish new packages nor act like a sponsor)

**Comment by JonMagon** [comment]
> > I created the request over two years ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973684
> > Given that [many packages have been in this state for many years](https://www.debian.org/devel/wnpp/being_packaged.html), I think this could be resolved in 2030.
> 
> Hi, thanks for your interest in Debian! Unfortunately, simply opening an ITP bug doesn't magically make the package available in the archive, the process is a bit more involved.
> 
> After opening the ITP (Intent To Package), you should publish your package on [mentors.debian.net](https://mentors.debian.net), a site where Debian Developers can review contributors' work and eventually upload the package in the archive, acting like a "sponsor" or "mentor".
> 
> Feel free to ask me anything if you have any doubt, I'll be happy to help :)
> 
> (I'm not a DD (Debian Developer) myself, I'm a DM (Debian Maintainer), meaning that I can only push updates to packages I already maintain, but cannot publish new packages nor act like a sponsor)

Hi.
It's a pity it takes so much rummaging to find the way.
Nice to meet you and thanks for the tip, I'll give it a try.

**Comment by JonMagon** [comment]
> https://mentors.debian.net/package/kdiskmark/ so that looks good... /me has a look at it
> 
> @JonMagon d/changelog: * Initial Release. (Closes: #973684) Version should not be 3.1.2 but 3.1.2-1 (it's not wrong) d/control: Vcs fields usually point to salsa.debian.org Standards-Version: 4.5.1 should be 4.6.2 Build-Depends clearly is wrong (missing many parts, for example: cmake, libaio-dev) Long description: KDiskMark is -> This is d/README: drop debian/upstream/metadata: please add this file debian/watch file should be easy too [spelling-error-in-binary](https://lintian.debian.org/tags/spelling-error-in-binary.html) inteface interface [usr/bin/kdiskmark]
> 
> are you on irc?
> 
> if you don't want to bother, i can add myself as co-maintainer and do these things?

Thank you. I started doing it back in January, but later had to put it off. If you really want to, I don't mind.

**Comment by alexmyczko** [comment]
https://ftp-master.debian.org/new/kdiskmark_3.1.3%2Bds-1.html

**Comment by JonMagon** [comment]
> https://ftp-master.debian.org/new/kdiskmark_3.1.3%2Bds-1.html

Looks great.

**Comment by alexmyczko** [comment]
You can now close this issue.

**Comment by Danny3** [comment]
Hey guys!
Thank you very much for adding it to Debian's repository!
It's much easier and faster to install it now.
And I can also add it to my post-install script to install all the packages I need.
I just tested the installation on Debian 12 + unstable repository and it was installed successfully.
But one thing that I wish it did automatically is to install all its dependencies.
After starting it I still see, in a pop-up window, this message:

>No FIO was found. Please install FIO before using KDiskMark.

And issuing the following command:

>sudo nala show kdiskmark

I see:

`
Package: kdiskmark
Version: 3.1.3+ds-2
Architecture: amd64
Installed: no
Priority: optional
Essential: no
Section: utils
Source: kdiskmark
Origin: Debian
Maintainer: ........ (edited by me to avoid spam)
Installed-Size: 655 KB
Depends: 
  libc6 (>= 2.34)
  libgcc-s1 (>= 3.0)
  libpolkit-qt5-1-1 (>= 0.112.0)
  libqt5core5a (>= 5.15.1)
  libqt5dbus5 (>= 5.0.2)
  libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1)
  libqt5network5 (>= 5.0.2)
  libqt5widgets5 (>= 5.2.0~alpha1)
  libstdc++6 (>= 5)
Conflicts: kdiskmark
Homepage: https://github.com/JonMagon/KDiskMark
Download-Size: 182 KB
APT-Sources: http://mirrors.nav.ro/debian/ unstable/main amd64 Packages
Description: simple open source disk benchmark tool for Linux distros
 This is an HDD and SSD benchmark tool with a very friendly
 graphical user interface. KDiskMark with its presets and powerful
 GUI calls Flexible I/O Tester and handles the output to provide an
 easy to view and interpret comprehensive benchmark result.

`
I see no dependency for that FIO package (I forgot what FIO stands for and which package I installed before to make it work).

And when I installed it with this command:

>sudo nala install kdiskmark

It downloaded and installed just this package:

>kdiskmark_3.1.3+ds-2_amd64.deb

So it clearly didn't download any dependency.

Is it possible to add this dependency too or at least mention in the message what is the package for FIO called?

Or is there a problem with adding the dependency?

I see that clicking on the OK button on that message, closes the program, so it's clearly a required dependency.
If there isn't any other problem, I'm ok with this and other programs requiring and downloading their dependencies when they are installed.

**Comment by alexmyczko** [comment]
Thank you for the report, this is indeed a bug, I will fix that by adding fio to Depends:

**Comment by alexmyczko** [comment]
@JonMagon didn't test, but can. trusted this place:

```
Required

    GCC/Clang C++17 (or later)
    [CMake](https://cmake.org/) >= 3.12
    [Extra CMake Modules](https://github.com/KDE/extra-cmake-modules) >= 5.73
    [Qt](https://www.qt.io/) with Widgets and DBus >= 5.9
    [PolicyKit](https://gitlab.freedesktop.org/polkit/polkit) Agent
        PolkitQt-1 bindings.
    [Flexible I/O Tester](https://github.com/axboe/fio) with libaio >= 3.1
        libaio development package.
```

**Comment by JonMagon** [comment]
> didn't test, but can. trusted this place:

A bad wording. I meant building fio from source.

**Comment by alexmyczko** [comment]
ah just fixed fio depends for kdiskmark will test to drop the extra build depends, nothing terrible if it is in though…

**Comment by JonMagon** [comment]
Thank you!

**Comment by Danny3** [comment]
Thank you very much!

I got the dependency installed through the normal system updates.
KDiskMark now opens without any problems or error messages, as expected.

For me, this issue is completely solved, as now the package, along with its dependencies are in Debian's repository, which makes it really easy to install and keep it up to date, so the issue can be closed.

**Comment by alexmyczko** [comment]
@Danny3 please close the issue then

**Comment by Danny3** [comment]
@alexmyczko, Thank you!
