### ISSUE TITLE
Requires root access for partitions that regular user has access anyway.

### ISSUE THREAD

**Issue by Mart-Bogdan** [JonMagon/KDiskMark#113]
- Linux-distro (kernel version): Manjaro Linux. Kernel: 5.15.85-1-MANJARO
- Desktop Environment (KDE/GNOME etc.): KDE 5.26.4
- Qt Version: 5.15.7
- KDiskMark Version: 3.1.2
- FIO Version: fio-3.33

### Description:

When you are asking to mark partiton that has full write access for current user, it still is asking for admin permissions.

![image](https://user-images.githubusercontent.com/775038/212219386-0c374ae0-10b6-4117-a0ac-25e2c29d3196.png)
![image](https://user-images.githubusercontent.com/775038/212219467-fe8ccdc8-c407-4061-a102-08d0f13a0b32.png)

 
### Steps To Reproduce:
Create new partiotion
Mount it
Make regular user owner of said partition root.
Try launching KDiskMark on said partition.

**Comment by JonMagon** [comment]
#101 duplication
