### ISSUE TITLE
[feature] Allow becnhmarking user's home, withput requireing root

### ISSUE THREAD

**Issue by Mart-Bogdan** [JonMagon/KDiskMark#114]
It shows my `/home` mount in drop-down, but said catalog requires root access to work with.

Would be nice if it run benchmark inside `/home/$USERNAME` instead. or use actuall $HOME with some fancy conditions. It it is on desired FS, or something.

So either just add $HOME as entry to drop-down, or detect it it is on desired FS and just use home instead of FS root.

**Comment by JonMagon** [comment]
New native versions of kdiskmark require root, as this allows the necessary functionality to be achieved. All operations are done through the rooted helper. Sharing the helper code with the main application is not practical.

**Comment by mystica555** [comment]
What precisely needs root access? if I can write to $HOME I want to be able to test as a normal user.
This seems wildly insecure to force root access for writing a file in my homedir.
