### ISSUE TITLE
an alternative to crystal disk info...

### ISSUE THREAD

**Issue by Heus-Sueh** [JonMagon/KDiskMark#116]
Is there a way to implement the features of crystal disk info? :thinking: , I think a "KDiskInfo" would be welcome
https://osdn.net/projects/crystaldiskinfo/

**Comment by gnarlin** [comment]
Doesn't Gnome Disks do this already? If you run it, then click the three vertical dot menu, click SMART Data & Self-Tests you get a screen which contains all the smart data of the drives and enables you to run different SMART disk tests.

**Comment by Heus-Sueh** [comment]
> Doesn't Gnome Disks do this already? If you run it, then click the three vertical dot menu, click SMART Data & Self-Tests you get a screen which contains all the smart data of the drives and enables you to run different SMART disk tests.

I think so, but a QT app like Crystal Disk Info would be much better and integrate better with KDE Plasma

**Comment by Ace-Krypton** [comment]
@Heus-Sueh After finishing with my benchmark tool, I will do an Info tool, it will be in QML/Qt/C++, probably I'll add assembly for CPUID instructions I dunno. If you have any recommendations, or any features you might want you could let me know

**Comment by Heus-Sueh** [comment]
> @Heus-Sueh After finishing with my benchmark tool, I will do an Info tool, it will be in QML/Qt/C++, probably I'll add assembly for CPUID instructions I dunno. If you have any recommendations, or any features you might want you could let me know

cool, I'll test it for sure, you providing an alpha I can go giving suggestions on how to improve.

**Comment by GrgMdmn** [comment]
I am also looking for that tool, I leave a comment to stay informed about an Info tool :)

**Comment by JonMagon** [comment]
Hi. Have a look at this repository: https://github.com/edisionnano/KDiskInfo
