### ISSUE TITLE
cmake Error - singleapplication does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by ericghara** [JonMagon/KDiskMark#123]
- Linux-distro (kernel version):  6.1.28-gentoo
- Desktop Environment (KDE/GNOME etc.): kde
- Qt Version:  5.15.10
- KDiskMark Version: 3.1.4
- FIO Version: fio-3.34
- cmake version: 3.26.4

### Description:
I get the following CMake error when trying to build from a cloned repo.  I do not get this error when I download release 3.1.4 archive.  This is a repeat of closed issue #105.

```
CMake Error at CMakeLists.txt:40 (add_subdirectory):
  The source directory

    /home/eric/Downloads/KDiskMark/src/singleapplication

  does not contain a CMakeLists.txt file.
```
 
### Steps To Reproduce:

```
git clone https://github.com/JonMagon/KDiskMark.git
cd KDiskMark/
git checkout 3.1.4
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release
```

I faced the same issue on a debian box as well.  I'll be honest I was hesitant to open this issue because it seems you are using a github action which essentially does what I did, and there was apparently no problem with the release... But nevertheless, it doesn't work on my boxes, so I am filing this.  Thanks.  I enjoyed the benchmark.

**Comment by JonMagon** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules

> You must run two commands: `git submodule init` to initialize your local configuration file, and `git submodule update` to fetch all the data from that project and check out the appropriate commit listed in your superproject
...
There is another way to do this which is a little simpler, however. If you pass `--recurse-submodules` to the `git clone` command, it will automatically initialize and update each submodule in the repository, including nested submodules if any of the submodules in the repository have submodules themselves.

**Comment by ericghara** [comment]
Thank you, I should have noticed that .gitmodules.  Cheers.
