### ISSUE TITLE
Kdismark

### ISSUE THREAD

**Issue by Jbelbus** [JonMagon/KDiskMark#125]
I'm just trying to install kdiskmark:
flatpak install flathub io.github.jonmagon.kdiskmark
Looking for matches…
but getting this error:
error: Nothing matches but getting this error: in remote flathub

I installed meteo y'day no probs, and it shows up

Any ideas? Thanks.

**Comment by JonMagon** [comment]
Could you perform `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` and then try again?
