### ISSUE TITLE
RND4KQ32T16 Bug

### ISSUE THREAD

**Issue by Ace-Krypton** [JonMagon/KDiskMark#127]
- Linux-distro (kernel version): Arch Linux, 6.4.10-arch1-1
- Desktop Environment (KDE/GNOME etc.): BSPWM
- Qt Version: 6.5
- KDiskMark Version: 3.1.3
- FIO Version: fio-3.35

### Description:
So, there's this issue with the RND4KQ32T16 module. As the name suggests, it's supposed to handle 16 threads with a numjobs value of 16. This usually means it takes a while to do its thing when you test it with fio.

But here's the catch: when you use it in your application, it's finishing way too early and spitting out the wrong results. And it's not just that – even when you peek at the Disk Read/Write stats from IOTOP, you can see it's around 300, while your app is just managing around 190. Weird, right?
 
### Steps To Reproduce:
https://github.com/JonMagon/KDiskMark/assets/75210504/b0c8fc57-87d7-49d4-86c5-eab781fe853b

**Comment by JonMagon** [comment]
KDIskMark aims to measure I/O against a filesystem. For random tests, the cost of operations is high. You can increase the time limit in the settings.

**Comment by Ace-Krypton** [comment]
I increased the time limit to 1 minute, still the same result
