### ISSUE TITLE
CrystalDiskMark compatibility profile

### ISSUE THREAD

**Issue by ivnish** [JonMagon/KDiskMark#128]
Hi!

I want a CrystalDiskMark compatibility profile.

Sec Q32T1
4KiB Q8T8
4KiB Q32T1
4KiB Q1T1

![transcend](https://github.com/JonMagon/KDiskMark/assets/29428813/6de154c0-a1c9-471e-946d-de5fe7b584fb)

I found this commit https://github.com/JonMagon/KDiskMark/commit/fde4ca51b817621e57a27482068a5fcc69067fec

Can I make a PR with a new profile?

Are you planning to add profiles as config files?

**Comment by JonMagon** [comment]
Hi. What's the new profile you're referring to? Numerical values? You can change them in the settings window.

**Comment by ivnish** [comment]
Oh, sorry. I overlooked an elephant)
