### ISSUE TITLE
Sometimes can't run certain tests..

### ISSUE THREAD

**Issue by CaptainCoward** [JonMagon/KDiskMark#132]
Manjaro 6.5.5
KDE
fio-3.35-1

It seems lke it is random working for me. Sometimes it would print out "bad FIO" tell me "No Fio" at start and sometimes it would work. Though it seems like it is actually never writing a file if i don'T explicitly choose it.

**Comment by CaptainCoward** [comment]
Yup i think it is realted to FIO. I just checked dmesg and saw that i get a lot of these 
`segfault at 0 ip 0000000000000000 sp 00007ffcb3b0cf98 error 14 in fio[55645e687000+1b000] likely on CPU 2 (core 2, socket 0)`

**Comment by JonMagon** [comment]
And try checking the AppImage, should be either way.

**Comment by CaptainCoward** [comment]
Ty AppImage worked, should have tried that first. :)

**Comment by JonMagon** [comment]
I think it's worth writing somewhere to Manjaro that the package is broken
