### ISSUE TITLE
Why SingleApplication?..

### ISSUE THREAD

**Issue by tbone2k-git** [JonMagon/KDiskMark#133]
I read in the description, that KDiskMark references SingleApplication library to prevent multiple application launches.
Is this optional somehow, or does KDiskMark only allow one instance by default?

If yes, I'm curious to why that limitation is there? I recall myself running multiple CrystalDiskMark instances on Windows to compare drives currently connected and to screenshot them alltogether e.g., so if possible, I'd like to be able to run multiple KDiskMark instances as well of course! o)

Thank you! o)

**Comment by JonMagon** [comment]
In the native package, benchmarking is done with a helper via DBus, which has only one instance at a time. Launching the second instance of the application itself is blocked so as not to cause errors. A flag to bypass this behavior [is planned](https://github.com/JonMagon/KDiskMark/issues/112).

You can still run multiple AppImage instances.
