### ISSUE TITLE
kdiskmark is giving inaccurate readings?

### ISSUE THREAD

**Issue by fennectech** [JonMagon/KDiskMark#136]
Is it possible for kdiskmark to give inaccurate readings?  I tested my array with your tool and it reported about 200 MB/s with a 6GB test file but using ddrescue to write zeros to the same FS on the same drive is averaging 600 MB/s    the load on the system is minimal the drive is under the same external load (seeding linux ISOs at a few hundred kb/s) in both tests  
the numbers are repeatable.

im sure none of the logic is to blame here  but is it possible that there is a bottleneck in FIO?    FS is btrfs     the results are accurate when i do the same test with my internal NVME drive

**Comment by JonMagon** [comment]
Depends on how exactly ddrescue works. Try selecting other test params or using other software.

**Comment by fennectech** [comment]
It was BTRFS compression.
