### ISSUE TITLE
"An error occurred while creating the benchmark file"

### ISSUE THREAD

**Issue by daninsky1** [JonMagon/KDiskMark#140]
- Linux-distro (kernel version): 5.15
- Desktop Environment (KDE/GNOME etc.): Gnome
- Qt Version: Idk
- KDiskMark Version: 3.1.4
- FIO Version: fio-3.1

### Description:
I've tried to test in a ntfs partition and showed this erros, and doesn't show anything useful on the terminal log.
Is pretty disapointing this useless message.

### Steps To Reproduce:
Try to run the benchmark on a nfts partition

**Comment by JonMagon** [comment]
Actually need to add details about the error here. No problem with ntfs, check that the user has write permissions to the directory.

**Comment by rrrexfield** [comment]
> Actually need to add details about the error here. No problem with ntfs, check that the user has write permissions to the directory.

which directory should I give permissions to? (I installed it using apt-get)
