### ISSUE TITLE
Why do the benchmark test results between KDiskMark and Gnome Disks not match?

### ISSUE THREAD

**Issue by AzizEmir** [JonMagon/KDiskMark#143]
- Linux-distro (kernel version): Debian 12 / 6.1.0-18-amd64
- Desktop Environment : Gnome
- Qt Version: -
- KDiskMark Version: 3.1.4
- FIO Version: - 

KDiskMark-3.1.4-fio-3.35-x86_64.AppImage

![diskbenchmark](https://github.com/JonMagon/KDiskMark/assets/101357256/c5484021-857c-4934-bcc0-c76ecdfab1dc)
![ddwriteresult](https://github.com/JonMagon/KDiskMark/assets/101357256/858604da-cbaa-491c-9b3a-d812b1715323)

**Comment by slackingfred** [comment]
I notice that your drive is LUKS encrypted. GNOME Disks tests the disk at block level, bypassing filesystems and thus LUKS. Both KDiskMark and `dd` tests at file level. So maybe the cost of LUKS en/decryption is source of the discrepancy you're seeing?
