### ISSUE TITLE
Consider switching to Qt 6

### ISSUE THREAD

**Issue by Integral-Tech** [JonMagon/KDiskMark#145]
[KDE Plasma 6](https://kde.org/announcements/megarelease/6/) was released several weeks ago, which is based on Qt 6. Maybe it's time to switch to Qt 6 for KDiskMark.

I am using KDE Plasma 6 on my laptop now.

**Comment by Samueru-sama** [comment]
Yeah turns out kdiskmark was what was preventing me from nuking qt5 from my system.

Good thing there's an available appimage in the releases, I just integrated that into my system to get rid of qt5 lol.

**Comment by JonMagon** [comment]
I updated the code to make the project build for Qt 6, but libpolkit-qt6-1-1 and libpolkit-qt6-1-1-dev are not available for Ubuntu right now, so it's not possible to build a binary deb archive using CI
