### ISSUE TITLE
KDiskMark does not consider all writable mount points

### ISSUE THREAD

**Issue by assarbad** [JonMagon/KDiskMark#15]
- Linux-distro: Ubuntu 20.04
- Desktop Environment (KDE/GNOME etc.): (Vanilla) GNOME
- Qt Version: 5.12.8
- KDiskMark Version: 1.6.2
- FIO Version: fio-3.16-1

### Description:

The combobox with the drives has several of them greyed out, despite them being mounted readwrite:

* `/` (ext4)
* `/boot/efi` (FAT32)
* `/data` (btrfs)

... whereas the following items are not greyed out:

* home folder (but won't work due to ecryptfs)
* `/mnt/DATA` an NTFS partition readwrite-mounted for the current user

The issue is that while the _root_ of `/data` - to give one example - isn't writable, some subfolders there are. So it should be viable somehow to benchmark that drive (e.g. by selecting a path explicitly?!).
 
### Steps To Reproduce:

Not sure at this point how you could reproduce it. I'll amend this report after I manage to test this on other systems.

**Comment by JonMagon** [comment]
It doesn't check if the drive is mounted in a writable mode, it checks if the user has permission to write.
Here you can see: https://doc.qt.io/qt-5/qfileinfo.html#isWritable
If you really want it, try to run KDiskMark as root.
What about your `/data` I know this issue and I will add possibility to type a directory path.

**Comment by assarbad** [comment]
> It doesn't check if the drive is mounted in a writable mode, it checks if the user has permission to write.

I'll admit it was my assumption, but there were indicators for and against that theory.

> Here you can see: https://doc.qt.io/qt-5/qfileinfo.html#isWritable

So basically the meaning of [`access(2)`](https://linux.die.net/man/2/access) with `W_OK` or similar. But the check seems to be at the root of the mount point still.

> If you really want it, try to run KDiskMark as root with `sudo`.

That worked nicely. I guess if I start using it more often I'll simply write some PolKit rules instead.

> What about your `/data` I know this issue and I will add possibility to type a directory path.

Cool. If you're aware of it and it's a planned feature, all the better.

**Comment by JonMagon** [comment]
I hope that's the most user-friendly solution what can be found. But if you have any idea how to improve it, please write.

**Comment by JonMagon** [comment]
You can test it here: https://github.com/JonMagon/KDiskMark/releases/tag/2.0.0-alpha
