### ISSUE TITLE
Vote for "Text-based user interface" without any dependancies on Desktop envrion or Qt

### ISSUE THREAD

**Issue by awoz** [JonMagon/KDiskMark#152]
- Debian, Arch, Fedora
- Desktop Environment (KDE/GNOME etc.):  none
- Qt Version: none

### Description:
Please add my vote for your todo "Text-based user interface" feature.

Sorry for tagging as bug. I don't know how to tag as a feature.

**Comment by JonMagon** [comment]
Hi. I'm not quite sure what you mean. As for the todo list, it's still on my radar, but I don't have the time to tackle it right now.

**Comment by HankB** [comment]
It's not clear to me either what is intended.

If by "Text-based user interface" @awoa means a CLI version, I'd suggest starting with the decent looking report shown in the README and adding

1. Command line options for needed settings
2. Eliminate the need for the GUI (and related libraries) to run the program - just run the benchmark as specified and print the text report.

Of course decisions like this are best made before coding starts. I have no idea if the code is  structure in a way to make separation of processing and display easy. I'm happy to have the program available as is but would be mildly interested in running it on headless servers.

I also wonder why this is tagged as a bug and not a feature request. I appreciate the need for @JonMagon to prioritize his efforts and think they might want to address bugs before new features.

best,

**Comment by awoz** [comment]
> It's not clear to me either what is intended.
> 
> If by "Text-based user interface" @Awoa means a CLI version, I'd suggest starting with the decent looking report shown in the README and adding
> 
>     1. Command line options for needed settings
> 
>     2. Eliminate the need for the GUI (and related libraries) to run the program - just run the benchmark as specified and print the text report.
> 
> 
> Of course decisions like this are best made before coding starts. I have no idea if the code is structure in a way to make separation of processing and display easy. I'm happy to have the program available as is but would be mildly interested in running it on headless servers.
> 
> I also wonder why this is tagged as a bug and not a feature request. I appreciate the need for @JonMagon to prioritize his efforts and think they might want to address bugs before new features.
> 
> best,
