### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by inf3rno** [JonMagon/KDiskMark#19]
Can you make a FreeBSD port? In theory everything is available, it is just that the FIO port does not have the libaio engine. https://www.freshports.org/benchmarks/fio/ There is a libaio port https://www.freshports.org/devel/linux-c7-libaio/ and Qt5 is available too https://www.freshports.org/devel/qt5/ I am not sure how hard it is to make it work, I don't speak C++.

**Comment by JonMagon** [comment]
I don't use FreeBSD and I don't plan to create a FreeBSD port.
Maybe someone wants to do it.

**Comment by inf3rno** [comment]
Ok, thanks!
