### ISSUE TITLE
Timeout for benchmarks is to short

### ISSUE THREAD

**Issue by raetiacorvus** [JonMagon/KDiskMark#2]
- Linux-distro: Arch Linux
- Desktop Environment (KDE/GNOME etc.): Gnome 
- Qt Version: 5.15.0
- KDiskMark Version: 1.5.0
- FIO Version: fio-3.19

### Description:
Currenty KDiskMark uses QProcess::waitForFinished with its default paramter of 30000 msec which is to short for most benchmarks to finish. e.g. with the current tests i get timeout errors on all tests on a hdd.
https://github.com/JonMagon/KDiskMark/blob/2c6f285836529ad7fa04675d0bce06b5057535dc/src/benchmark.cpp#L55

**Comment by JonMagon** [comment]
Probably that wasn't good idea to limit benchmark time, there must be another way to inform user when test takes a long time. Check if resolved in https://github.com/JonMagon/KDiskMark/commit/2cb8612be74221ef81099c907598296795b013b3

**Comment by raetiacorvus** [comment]
Yes 2cb8612 solves the timeout issue, thank you
