### ISSUE TITLE
Flatpak or Snap version of KDiskMark

### ISSUE THREAD

**Issue by TroelsS** [JonMagon/KDiskMark#34]
Any chance for a flatpak or snap version of KDiskMark?

**Comment by JonMagon** [comment]
I plan to create this in the near future.

**Comment by JonMagon** [comment]
https://github.com/JonMagon/KDiskMark/commit/720c96632616995e9a475daf3bfeb220cdc3e9c1 adds instruction for the snap
I've requested auto-connections on the snapcraft but I don't know how long does a review take. Currently, you have to connect interfaces manually. I don't close the issue because this is not yet fully solved.

**Comment by TroelsS** [comment]
I just installed via snapcraft and everything seems to work as it should. Thanks!

**Comment by JonMagon** [comment]
Unfortunately, I report that most likely some of the functionality will not be available in the Snap package. As I understand it, it cannot be made to work with polkit. It seems to be possible only if the confinement is equal to classic, but there are difficulties with building the Qt program. I'll continue to support the Snap package, but will have to add an appropriate startup notification. If someone can build the correct Snap or Flatpak package, I would be very grateful.

**Comment by palette-dev** [comment]
I want to make a flatpak manifest for this project, I'll look into it in a few days when I get the time to do it, until then I'll leave this comment here so I won't forget

**Comment by WojtasJD** [comment]
Is KDiskMark snap version  hidden from search?

https://snapcraft.io/search?q=kdiskmark
(We couldn't find anything for your search [...])

Same behaviour under Ubuntu "snap-store"  app.

but here it is: https://snapcraft.io/kdiskmark

**Comment by JonMagon** [comment]
> Is KDiskMark snap version hidden from search?
> 
> https://snapcraft.io/search?q=kdiskmark (We couldn't find anything for your search [...])
> 
> Same behaviour under Ubuntu "snap-store" app.
> 
> but here it is: https://snapcraft.io/kdiskmark

Hi. Snap package is hopelessly outdated.
