### ISSUE TITLE
benchmarks fail to run on button click

### ISSUE THREAD

**Issue by takbal** [JonMagon/KDiskMark#39]
- KDiskMark Version: 2.0.0 (commit  f12d789 of benchmark.cpp)

### Description:

The app does not start the benchmarks when clicking on the buttons.

### Steps To Reproduce:

Happens on my rig in all runs after compiling from source. Also present in the version that can be downloaded via apt.

### Likely reason:

Lingering variable init. The Benchmark class in benchmark.cpp does not initialise the m_running member, hence it inits to  random. Adding

m_running = false;

to the Benchmark constructor fixes the problem.

**Comment by JonMagon** [comment]
What compiler do you use?

вт, 1 дек. 2020 г., 15:25 takbal <notifications@github.com>:

**Comment by takbal** [comment]
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by JonMagon** [comment]
Oops, it's really not initialized. I missed a linter's warning.

**Comment by JonMagon** [comment]
Now should be fixed https://github.com/JonMagon/KDiskMark/commit/5104b2be9bae490699add803ae4f40e398d01973

**Comment by ufechner7** [comment]
Same happens with the Ubuntu packages from the ppa. Any new release planned?

**Comment by JonMagon** [comment]
Could you please build the latest commit?

**Comment by ufechner7** [comment]
I managed to build the last commit even on Ubuntu 18.04. Perhaps you can mention in the README that this works and the qt version is not too old. Had to install:
sudo apt install extra-cmake-modules
sudo apt install qttools5-dev
which is not obvious and might also be worth to mention in the README.

So yes, working fine now! Thank you.

**Comment by JonMagon** [comment]
> which is not obvious and might also be worth to mention in the README.
This is already mentioned in `Dependencies`.

I will release a new version after solving #38

**Comment by JonMagon** [comment]
Now fixed for snap.
