### ISSUE TITLE
Does not autodetect encrypted devices

### ISSUE THREAD

**Issue by galvanized** [JonMagon/KDiskMark#4]
- Linux-distro: Ubuntu 18.04.5 LTS
- Desktop Environment (KDE/GNOME etc.): GNOME
- Qt Version: 5.9.5
- KDiskMark Version: source (7321b05)
- FIO Version: fio-3.21-41-gf0ed

### Description:

Mounted encrypted volumes do not appear in the device-selection drop-down. 
All my mounted unencrypted partitions appear in the drop-down as expected (these all appear under /dev/sd__).
None of my mounted encrypted partitions appear in the drop-down (/dev/dm-_).

 
### Steps To Reproduce:

1. Mount a encrypted filesystem.
2. Launch KDiskMark.
3. Notice the filesystem is not present in the device selection.

**Comment by JonMagon** [comment]
Please check now. I haven't yet resolved the problem with showing encrypted device model, but benchmarking seems to be working.
