### ISSUE TITLE
ARM supports, please

### ISSUE THREAD

**Issue by GF-Huang** [JonMagon/KDiskMark#42]

**Comment by JonMagon** [comment]
Could you describe in detail the problem?

**Comment by GF-Huang** [comment]
Raspberry Pi (RPi) is ARM arch, I want to install `KDiskMark` on RPi without building by myself.

**Comment by JonMagon** [comment]
Fedora/Arch/Manjaro have armv7/armv7hf/aarch64 package

**Comment by JonMagon** [comment]
There's no kdiskmark in repos on the screenshot, you should build it or use snap: https://snapcraft.io/install/kdiskmark/raspbian

**Comment by JonMagon** [comment]
There's no kdiskmark in repos in the screenshot, you should build the application or use snap: https://snapcraft.io/install/kdiskmark/raspbian

**Comment by GF-Huang** [comment]
![Uploading image.png…]()

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/103659796-c9e08780-4fa7-11eb-80ff-063ae99e03ee.png)

**Comment by JonMagon** [comment]
Ah sorry, I forgot about it. There's only an amd64 package in snap, because of `kde-frameworks-5-core18` which exists only for amd64.

**Comment by JonMagon** [comment]
PPA contains arm64 and armhf packages now.

**Comment by petesimon** [comment]
PPA link for ubuntu??
