### ISSUE TITLE
Runs only using sudo on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by raelgc** [JonMagon/KDiskMark#47]
- Linux-distro: Ubuntu 20.04.2
- Desktop Environment (KDE/GNOME etc.): Gnome 3.38 (Default Ubuntu 20.04)
- Qt Version: 5.12.8
- KDiskMark Version: 2.2.0
- FIO Version: fio-3.16

### Description:

If I starts the application without `sudo`, nothing happens on click in the buttons. Not even errors in the terminal.

In the other side, if I start the application using `sudo`, it works.
 
### Steps To Reproduce:

1. Start kdiskmark 
2. Click on any button to start.

### Expect Results

Disk test starts.

### Current Results

Nothing happens.

**Comment by JonMagon** [comment]
Did you install from PPA or build yourself?

**Comment by JonMagon** [comment]
Can't confirm on Ubuntu 20.04.1, GNOME 3.36.3. I don't know if there are some important updates, will check it on the newer version.

**Comment by raelgc** [comment]
@JonMagon thanks for the quick answer, and thanks for the awesome application!

I've installed downloading the `.deb` file from the [Releases](https://github.com/JonMagon/KDiskMark/releases/tag/2.2.0) page.

I'll try now with the PPA and will report if it works.

**Comment by raelgc** [comment]
Installing from the PPA, it properly asks for the `sudo` password, which doesn't happen when installing the `.deb` from the Releases page. Wondering if it's something different between them in the `.desktop` file.

**Comment by JonMagon** [comment]
Hm, strange. I'll try to find out what's wrong.

**Comment by JonMagon** [comment]
It installs `org.jonmagon.kdiskmark.conf` to `/usr/etc/dbus-1/system.d`, looks like it should be `/usr/local` or `/usr/share` instead of just `/usr`.

**Comment by JonMagon** [comment]
The same issue with the RPM package built via GH CI.

**Comment by JonMagon** [comment]
Likely fixed in https://github.com/JonMagon/KDiskMark/commit/3a3444193bce685026722aec92fa231b025d92f2
It is definitely not a good solution. I read about CMake/CPack flags but nothing found.
Anyway, it should nothing break in the future. The binary packages for the latest release were again uploaded. Please check it.

**Comment by raelgc** [comment]
Just downloaded from Releases and now it properly requested the `sudo` password before run.

**Comment by JonMagon** [comment]
So I think we could mark the issue as solved. If I'll find a better solution, I will update. It affects only GitHub workflows.
