### ISSUE TITLE
Random Reads getting stuck and not completing passes. System unresponsive.

### ISSUE THREAD

**Issue by le-corbeau** [JonMagon/KDiskMark#49]
- Linux-distro (kernel version): 5.9.16-1-MANJARO
- Desktop Environment (KDE/GNOME etc.): KDE Plasma 5.21.2
- Qt Version: 5.15.2
- KDiskMark Version: 2.2.0
- FIO Version: fio-3.25

### Description:
RND4KQ32T16 and RND4KQ1T1 checks never finish a single pass. Always stuck at pass 0/5. Iotop shows the fio processes running and disk reads 90-99% IO and Total Disk Read around 1500-1600 K/s. System gets very unresponsive during the time.
I have let it run for around 15min but it still stays at Random Read pass 0/5.

 
### Steps To Reproduce:
1 Launch KDiskMark 2. Start RND4KQ32T16 or RND4KQ1T1

**Comment by JonMagon** [comment]
You are using a rather slow device, choose a smaller file size.

**Comment by le-corbeau** [comment]
I switched to 512MiB file size. Still stuck at 0/5 during randread. Left it running for about 15 minutes. Attaching a screenshot for reference.
![kdiskmark_randread_512MiB](https://user-images.githubusercontent.com/19852921/110911666-ffec1000-8338-11eb-98b5-f1833c57f1d1.png)

**Comment by JonMagon** [comment]
Based on the results of the sequential read in the screenshot above, the file size is still too big to get results for a random read in a short time. I would recommend setting the file size to 16MB, so you don't have to wait half a day. In this case, RND4KQ32T16 is likely to take longer to execute than RND4KQ1T1. Generally, random reading is quite a hard situation for HDD, because there is a very frequent read head relocation. You just have to wait for the job to complete.

**Comment by le-corbeau** [comment]
I took your advice and switched to 16MiB. It seems to have worked. I noticed the Total Disk Read rate is higher while using file size 16MiB. Attaching the results for reference. Are the metrics with 16MiB file size decent indicators for performance? Is it expected of my PC to seize up and get unresponsive during random reads? I have been trying to diagnose what is causing this issue.






![kdiskmark_16MiB_results](https://user-images.githubusercontent.com/19852921/110926038-e8695300-8349-11eb-8077-b3ec3b3425a0.png)
![kdiskmark_randread_16MiB](https://user-images.githubusercontent.com/19852921/110926041-e901e980-8349-11eb-9ae1-3abe2d4010b3.png)

**Comment by JonMagon** [comment]
The screenshot shows fio reading at 1014.76 K/s at the moment, the rest are other processes. If you try to do anything else during the test, other processes may be waiting a long time for I/O operations. Like if you open an application it has to load from disk into memory first, plus load some additional files, or if you surf the web the browser will periodically read and write the browser cache. The effect of this can be reduced, although it's unlikely if you disable the option to clear the page cache in KDiskMark settings. This can be done if you do not get unreal results when you disable it, such as 600 MB/s. All this only affects HDD and possibly slow USB drives. SSD and NVME are able to perform remarkably well even during the test.

**Comment by le-corbeau** [comment]
Thanks for your help. I am now looking into buying a new SSD. I face the same unresponsiveness when I am copying files from my external HDD to my PC. During the test my system was so unresponsive that even the screenshot took a long time to register after pressing PrtSc. I know my HDD is slow and old but I wanted to get an idea of exactly how slow.

**Comment by JonMagon** [comment]
> Different sizes for different tests

CrystalDiskMark limits the testing time. I will prepare a KDiskMark release with the same functionality.

**Comment by dmatora** [comment]
Thank you
