### ISSUE TITLE
wrong multi threaded performance

### ISSUE THREAD

**Issue by gitthangbaby** [JonMagon/KDiskMark#5]
- Linux-distro: manjaro
- Desktop Environment (KDE/GNOME etc.): KDE
- Qt Version: 
- KDiskMark Version: 1.5.1
- FIO Version: fio-3.21

### Description:
just like the screenshot on this webpage shows the performance of RND4K Q32T16 where T>0 is way too low. It should much higher than Q1T1 performance.
that's not reproduced with fio --threads and not reproduced with crystaldiskmark with the same drives.
to override: set T=1 and watch performance grow tenfold on NVME
nothing in the "Profile" menu so far

### Steps To Reproduce:
use default profile and watch the result in 3rd line

note: since test folder is forced to be home folder, it's a bit struggle to test disk performance if home folder is encrypted

**Comment by JonMagon** [comment]
Please check https://github.com/JonMagon/KDiskMark/commit/3033c56aca925e07e4f6cc803c9cae0a9c66f12e
It should be fixed I think

**Comment by gitthangbaby** [comment]
thanks, got it from AUR and it works
