### ISSUE TITLE
Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by hmsjy2017** [JonMagon/KDiskMark#51]
- Linux-distro (kernel version): Raspbian buster armhf
- Desktop Environment (KDE/GNOME etc.): PIXEL (based on LXDE)
- Qt Version: /
- KDiskMark Version: /
- FIO Version: /

### Description:
```
Cannot install normally via deb packages.(from ppa)

Note, selecting 'kdiskmark' instead of '/home/pi/kdiskmark.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kdiskmark : Depends: libkf5authcore5 (>= 5.56.0) but it is not installable
             Depends: libqt5core5a (>= 5.14.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
E: Unable to correct problems, you have held broken packages.
```

 
### Steps To Reproduce:
Install KDiskMark on Raspberry Pi via deb packages.

**Comment by RDKRACZ** [comment]
Is your system up-to-date? (try using `sudo apt update` and `sudo apt upgrade`) I can't find `libkf5authcore5` in Debian Buster repos https://packages.debian.org/buster/allpackages but I can in Ubuntu's https://packages.ubuntu.com/groovy/libkf5authcore5. Do `apt search libkf5authcore5` and post the output here. Probably your repos have too old version of libkf5authcore5 or don't include it at all.

**Comment by hmsjy2017** [comment]
> Is your system up-to-date? (try using `sudo apt update` and `sudo apt upgrade`) I can't find `libkf5authcore5` in Debian Buster repos https://packages.debian.org/buster/allpackages but I can in Ubuntu's https://packages.ubuntu.com/groovy/libkf5authcore5. Do `apt search libkf5authcore5` and post the output here. Probably your repos have too old version of libkf5authcore5 or don't include it at all.

It is not in the Raspbian official repository. But I find it in the Debian official repository.

**Comment by JonMagon** [comment]
All deb packages in the PPAs are primarily for Ubuntu. They may work in other distributions as well, but no one guarantees this. Especially if you are running Raspbian, which is based on Debian. You have to build it yourself.
