### ISSUE TITLE
Report disk model under FreeBSD

### ISSUE THREAD

**Issue by danfe** [JonMagon/KDiskMark#52]
I've added your program to FreeBSD ports and had to patch it a bit so it reports disk model correctly; would be nice if you could merge [the patch](https://cgit.freebsd.org/ports/diff/sysutils/kdiskmark/files/patch-src_diskdriveinfo.cpp?id=c769e65b01c65830ca6e98a3ff0a6ef02c2f9438), it's rather small and simple.  Of course, I've forgotten to `close(fd)` before returning from the function. :-(

**Comment by JonMagon** [comment]
Hi! Thank you. Why is there [sys/fcntl.h included](https://cgit.freebsd.org/ports/tree/sysutils/kdiskmark/files/patch-src_diskdriveinfo.cpp?id=c769e65b01c65830ca6e98a3ff0a6ef02c2f9438#n9)? Maybe it is better to use QFile, which is already included in `diskdriveinfo.cpp`?

**Comment by danfe** [comment]
> Why is there `sys/fcntl.h` included?

To get `O_RDONLY` definition.

> Maybe it is better to use QFile, which is already included in `diskdriveinfo.cpp`?

Isn't QFile mainly for reading and writing files, while here we open device node to call `ioctl()` on it?

**Comment by JonMagon** [comment]
> Isn't QFile mainly for reading and writing files, while here we open device node to call `ioctl()` on it?
Oh right, I read the code wrong. I'll create a commit.

**Comment by danfe** [comment]
Thanks!  I forgot to mention that `close(2)` needs `#include <unistd.h>` but I guess that can wait for another day.

**Comment by JonMagon** [comment]
I couldn't check, is it okay now?

**Comment by danfe** [comment]
Yup, it's fine, thanks!
