### ISSUE TITLE
HiDPI not scaling correctly

### ISSUE THREAD

**Issue by WMRamadan** [JonMagon/KDiskMark#54]
- Linux-distro (kernel version): Pop OS 20.10 Kernel 5.11.0-7614-generic
- Desktop Environment (KDE/GNOME etc.): GNOME 3.38.3 (X11)
- Qt Version: 
- KDiskMark Version: 2.2.0
- FIO Version: fio-3.16

### Description:
KDiskMark display does not scale using 4K (3840x2160) at 150% scale
![Screenshot from 2021-06-04 17-32-28](https://user-images.githubusercontent.com/1612303/120818032-e8e54480-c55a-11eb-9229-dfa7caad09c6.png)

 
### Steps To Reproduce:
Download deb package from releases github link

**Comment by JonMagon** [comment]
```
QT_AUTO_SCREEN_SCALE_FACTOR=1 kdiskmark
```

**Comment by WMRamadan** [comment]
> ```
> QT_AUTO_SCREEN_SCALE_FACTOR=1 kdiskmark
> ```

Yes this works, but it should be auto-scaled at the start of the application from GUI launch.

**Comment by JonMagon** [comment]
There is no other way to make a qt application work properly on hidpi.

**Comment by WMRamadan** [comment]
> There is no other way to make a qt application work properly on hidpi.

I believe Qt 6 supports this:
https://doc.qt.io/qt-6/highdpi.html
