### ISSUE TITLE
The HDD test takes a very long time.

### ISSUE THREAD

**Issue by kuzyaka62** [JonMagon/KDiskMark#60]
The HDD test has been going on for a very long time, for more than 6 hours and it is not known when it will end.
At the same time, the same SSD tests take no more than half an hour.
Is this how it should be?
![wd1](https://user-images.githubusercontent.com/82034544/138122481-ca514989-a64b-4fbd-a161-2cbce83f879c.png)
![wd2](https://user-images.githubusercontent.com/82034544/138122482-7ed95e12-376c-4b1d-a85a-15f373895607.png)

**Comment by JonMagon** [comment]
Duplication of #49
