### ISSUE TITLE
PolKit dialog pops up halfway through and fails process

### ISSUE THREAD

**Issue by gudvinr** [JonMagon/KDiskMark#65]
- Linux-distro (kernel version): Arch Linux (Linux 5.15.6-zen2-1-zen)
- Desktop Environment (KDE/GNOME etc.): KDE (Plasma 5.23.4, Frameworks 5.88.0, X11)
- Qt Version: 5.15.2
- KDiskMark Version: 2.2.1
- FIO Version: fio-3.28

### Description:

After starting benchmark KDiskMarks shows PolKit prompt to clear pagecache. After I enter password it starts benchmarking process until, at some point, PolKit prompt appears again.

If I enter password again it won't continue operation but fails with FIO-related error which I didn't write down but it sounds rather generic.
 
### Steps To Reproduce:  
1. Start Benchmark
2. Wait

**Comment by JonMagon** [comment]
Can't be fixed, the authorization period for polkit is hardcoded and equals 5 minutes: https://cgit.freedesktop.org/polkit/tree/src/polkitbackend/polkitbackendinteractiveauthority.c#n3271

**Comment by gudvinr** [comment]
It can be implemented using another approach though.  
This limit only shows that you shouldn't use polkit for this particular actions during long-running tasks.

If, instead, kdiskmark would run separate process as root when you start benchmarking, that could eliminate need to enter passwords or manually start application from root. Either is unnecessary tedious.

And even without that at least process shouldn't fail when you didn't act on this prompt for a while.
