### ISSUE TITLE
Doesn't work with /home

### ISSUE THREAD

**Issue by kartun83** [JonMagon/KDiskMark#66]
- Linux-distro (kernel version): Mint 20.2 5.15.9-051509-generic #202112161532 SMP
- Desktop Environment (KDE/GNOME etc.): Cinnamon
- Qt Version: 
- KDiskMark Version: 2.3.0
- FIO Version: fio-3.16

### Description:
Choosing any directory in /home doesn't allow to perform tests

 
### Steps To Reproduce:
Select directory in /home/$user

**Comment by JonMagon** [comment]
Could you provide more information?

**Comment by youling257** [comment]
I mount /dev/sda1 on /1, choose /1 directory, benchmark failed.

**Comment by youling257** [comment]
I used "cmake -D PERFORM_PAGECACHE_CLEARING_USING_KF5AUTH=OFF .." to build kdiskmark, run benchmark no problem.

**Comment by youling257** [comment]
I install kdiskmark_2.3.0_amd64.deb, run kdiskmark as root, no anything directory found.
run my build kdiskmark as root, can found directory.
![_20211231_133538](https://user-images.githubusercontent.com/16304724/147805539-25980788-f175-4106-8366-7bfc7d45853e.JPG)
![_20211231_133507](https://user-images.githubusercontent.com/16304724/147805547-e6fc18fe-afb7-4326-ac91-56678f1ab71f.JPG)

**Comment by JonMagon** [comment]
The structure of the file system is quite strange. Since you write that when running as a non-root user the directories are not displayed and the benchmarking fails, it is likely that the normal user does not have access to these directories.

**Comment by youling257** [comment]
i write i running kdiskmark as root user always, running the deb package kdiskmark as root.
running my build kdiskmark as root user.

**Comment by JonMagon** [comment]
What distribution do you use?

**Comment by youling257** [comment]
ubuntu Jammy Jellyfish

**Comment by JonMagon** [comment]
Okay, I'll test it and come back later.

**Comment by youling257** [comment]
dpkg -i kdiskmark_2.3.0_amd64.deb, apt --fix-broken install, install libkf5auth5, the directories are not displayed.
install a package from PPA, libkf5auth5 needn't, auto remove libkf5auth5, the directories are displayed.
but my problem still exists with ppa package. my build kdiskmark binary no problem.
![_20211231_212930](https://user-images.githubusercontent.com/16304724/147825839-ebaf053f-6ef8-48f0-8fc4-3f64fb311640.JPG)
![_20211231_212943](https://user-images.githubusercontent.com/16304724/147825848-3f5543ee-77d8-4313-bec1-deb36087313a.JPG)
You can't recreate my test environment, my test environment can't say clear.

**Comment by youling257** [comment]
in my test environment,

kf.auth: Tried to start an invalid action:  "org.jonmagon.kdiskmark.dropcache"
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)



qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: XKeyboard extension not present on the X server
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 509, resource id: 16778335, major code: 40 (TranslateCoords), minor code: 0

** (kdiskmark:29210): CRITICAL **: 21:35:40.748: polkit_system_bus_name_new: assertion 'g_dbus_is_unique_name (name)' failed

(kdiskmark:29210): GLib-GObject-CRITICAL **: 21:35:40.748: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
kf.auth: Tried to start an invalid action:  "org.jonmagon.kdiskmark.dropcache"
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
