### ISSUE TITLE
Drive space used in % and GB used isn't shown correctly

### ISSUE THREAD

**Issue by sys-256** [JonMagon/KDiskMark#67]
### My system
- Linux distro: Kubuntu 20.04.3 LTS, 5.11.0-43-generic, x86_64
- Desktop Environment: KDE Plasma 5.18.5, KDE Frameworks 5.68.0
- Qt Version: 5.12.8
- KDiskMark Version: 2.3.0
- FIO Version: fio-3.16

### Description:
If you select a folder (no matter where, both on / and /home/bram for me) it shows an incorrect value at percentage and GB's used, see these screenshots:
![kdiskmark-1](https://user-images.githubusercontent.com/84628826/147705118-1182c4aa-5c7c-4735-af46-d810c88432ae.png)
![kdiskmark-2](https://user-images.githubusercontent.com/84628826/147705122-9155e427-7ecf-44b5-a606-bc69b91fc750.png)

 
### Steps To Reproduce:
Select a folder, and you'll see the drive space used in % and GB used isn't shown correctly

**Comment by JonMagon** [comment]
These values represent free space, not occupied space. See #35

**Comment by sys-256** [comment]
Ah okay, then it shows it correctly.
