### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by orena1** [JonMagon/KDiskMark#78]
Linux colab03 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

![Screenshot_20220406_151515](https://user-images.githubusercontent.com/8983713/162050998-66819311-c87f-43a8-be9f-85fd28febf29.png)

### Description:

I click All and it is just stuck on the start page:
![Screenshot_20220406_151515](https://user-images.githubusercontent.com/8983713/162050970-d05580c1-5352-4339-b592-e940dcab5155.png)

Anyway to get any debug info ? 
Thanks

**Comment by JonMagon** [comment]
I see it says flash drive, are you sure nothing is happening? 1 GB for a
flash drive is a lot and may take a long time to test. Try choosing a
smaller file size. The latest version of kdiskmark has a time limit. What
version are you using?

**Comment by orena1** [comment]
It started working after I restarted the computer, not sure why.
BTW, why do you need admin permissions?
Thanks!
