### ISSUE TITLE
Can not install with snap

### ISSUE THREAD

**Issue by aleksey-pro** [JonMagon/KDiskMark#79]
- Linux-distro (kernel version): Raspberry PI OS - Debian x64
- Desktop Environment (KDE/GNOME etc.): Debian
- Qt Version: 
- KDiskMark Version: latest
- FIO Version: fio-#.#

### Description:

Can not install with snap
 
### Steps To Reproduce:

sudo snap install kdiskmark
get error - 
```
error: snap "kdiskmark" is not available on stable but is available to install on the following
       channels:

       beta       snap install --beta kdiskmark
       edge       snap install --edge kdiskmark

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info kdiskmark'.

```
when I choose 
`snap install --beta kdiskmark `
get error - 
```
error: snap "kdiskmark" is not available on beta but is available to install on the following
       channels:

       edge       snap install --edge kdiskmark

       Get more information with 'snap info kdiskmark'.
       
```
when I choose 
`snap install --edge kdiskmark `
get error - 
```
sudo snap install --edge kdiskmark
error: snap "kdiskmark" is not available on latest/edge but other tracks exist.

       Please be mindful that different tracks may include different features. Get more information
       with 'snap info kdiskmark'.

```

**Comment by JonMagon** [comment]
Are you sure the architecture is amd64? The package is not available for ARM.
[You can check here ](https://snapcraft.io/kdiskmark) that the package is in a stable channel.

**Comment by aleksey-pro** [comment]
thanx

**Comment by aleksey-pro** [comment]
add-apt-repository ppa:jonmagon/kdiskmark
is it possible to update repositoty? ppa is old and depricated, so  can not be installed to Debian bullseye

**Comment by JonMagon** [comment]
PPA is totally fine. Debian does not support PPAs. You have to build the package yourself or use a different distribution. I do not provide Debian packages.
