### ISSUE TITLE
Cant run Kdiskmark as sudo, crashed immediately

### ISSUE THREAD

**Issue by IdontKnowWhatToNameThisAccount** [JonMagon/KDiskMark#80]
- Linux-distro (kernel version): Linux Mint 20.3 (5.4.0-91-generic)
- Desktop Environment : Cinnamon
- Qt Version: couldnt even find out to to check that
- KDiskMark Version:2.3.0
- FIO Version: fio-3.1

### Description:
Installed Kdsikmark through snap, running it without sudo has the following command line output, but the program works fine:
```
user123@user123-ubuntu:~$ kdiskmark
Qt: Session management error: Could not open network socket
```
Running it as sudo has this output, the program window never opens:
```
user123@user123-ubuntu:~$ sudo kdiskmark
mkdir: cannot create directory '/run/user/0': Permission denied
No protocol specified
qt.qpa.xcb: could not connect to display :0
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/0/snap.kdiskmark', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/0/snap.kdiskmark', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/0/snap.kdiskmark', please create it with 0700 permissions.
no screens available, assuming 24-bit color
Segmentation fault
```

### Steps To Reproduce:
1. install snap on linux mint
2. install kdiskmark through snap
3. run kdiskmark or sudo kdiskmark

**Comment by JonMagon** [comment]
You should never run GUI applications with `sudo`. Use `kdesu`.

**Comment by rshalaev** [comment]
When starting kdiskmark from user account - it complains that results will be inaccurate. Would be helpful to have instructions on how to address. `kdesu` is not installed by default, so perhaps it should be listed in dependencies, and it's use explained.

**Comment by rshalaev** [comment]
Update - I tried installing Kdiskmark with `apt` instead of `snap` - now warning is gone, and application requests elevated mode after starting up (as expected). IMHO Snap package is broken
