### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by eoksum** [JonMagon/KDiskMark#83]
Hi there

I'm trying to run KDiskMark 2.3.0 on a CentOS 7 server but I keep getting this error:
<pre>
[root@vultr ~]# rpm -i kdiskmark-2.3.0-1.x86_64.rpm
error: Failed dependencies:
        libstdc++.so.6(CXXABI_1.3.9)(64bit) is needed by kdiskmark-2.3.0-1.x86_64
</pre>

But libstdc++ is of course there:
/usr/lib64/libstdc++.so.6

Any ideas how I can fix this issue?
Thanks.

**Comment by JonMagon** [comment]
I'm not sure, but maybe the ABI version is not 1.3.9?

**Comment by eoksum** [comment]
I think it was 1.3.9 but I'm not 100% sure. It was running on CentOS 7 with latest packages installed.

**Comment by JonMagon** [comment]
Could you check GCC version? `gcc --version`
It should be greater than 5.1.0 for 1.3.9 ABI
