### ISSUE TITLE
The name org.jonmagon.kdiskmark was not provided by any .service files

### ISSUE THREAD

**Issue by jconnolly837** [JonMagon/KDiskMark#85]
- Void Linux (5.18.17_1)
- KDE 5.25.3
- Qt Version: 5.15.5
- KDiskMark Version: 2.3.0
- FIO Version: fio-3.31

### Description:
Upon trying to run any of the benchmarks, I get the following error message.
![Screenshot_20220816_004848](https://user-images.githubusercontent.com/26425730/184807097-3eea3171-e7b1-473f-a991-a93da14ec6e3.png)
`DBus Backend error: service start org.jonmagon.kdiskmark failed: The name org.jonmagon.kdiskmark was not provided by any .service files`
 
### Steps To Reproduce:
1. Git clone from master.
2. Successfully build.
3. Run kdiskmark from within the build directory.
4. Try to run a benchmark, accepting to overwrite ⁠~/⁠.kdiskmark.tmp
5. Receive error message mentioned above, without any terminal output.

**Comment by JonMagon** [comment]
Hi. If the application is built with KAuth support, it must be installed as a complete package so that all the necessary files get to where they need to be. How to build the package: https://github.com/JonMagon/KDiskMark#building-a-package-using-cpack

**Comment by jconnolly837** [comment]
I've tried building it with KF5AUTH_USING=OFF and I'm getting the same error. I've also tried using cpack to make a ZIP package and unpacking it to root. It was a successful unpack because I now have kdiskmark in $PATH, but I'm still getting the same error.

**Comment by JonMagon** [comment]
> I've tried building it with KF5AUTH_USING=OFF and I'm getting the same error.

Can't reproduce.
```
git clone https://github.com/JonMagon/KDiskMark.git
cmake -D KF5AUTH_USING=OFF ..
cmake --build .
```
There isn't org.jonmagon.kdiskmark and kdiskmark does not require it.

Back to the question about KAuth. Apparently, you need to manually move the .service file to your `polkit-1/actions` directory depending on the distro

**Comment by jconnolly837** [comment]
I see my issue. I was using just make when I should have been using cmake. Kdiskmark is working fine now.
