### ISSUE TITLE
KDiskMark3 second instance - D-Bus interface is already in use.

### ISSUE THREAD

**Issue by WojtasJD** [JonMagon/KDiskMark#88]
- Linux-distro (kernel version): Ubuntu 22.04 (5.15.0-25-generic) x86-64
- Desktop Environment (KDE/GNOME etc.): GNOME 42.0 (X11)
- Qt Version: 5.15.3
- KDiskMark Version: 3.0.0
- FIO Version: fio-3.28

### Description:
Unable to run KDiskMark 3.0.0 multiple instances.

 
### Steps To Reproduce:
Install KDiskMark 3.0.0, launch it and then launch another instance

![Screenshot from 2022-08-24 16-47-18](https://user-images.githubusercontent.com/17054153/186476920-d38d23b9-7d70-4044-a5b0-fcc54b9c8145.png)
.

**Comment by JonMagon** [comment]
In fact, this is expected behavior, isn't it? The helper registers the name by which it communicates with the main application. Only one connection can be established at a time. Or it might be worth limiting the number of copies of kdiskmark so that a new window cannot be created.

**Comment by WojtasJD** [comment]
So this will be a limitation of the new version? 
With version 2.3.0 I can have multiple instances of KDiskMark running.

**Comment by JonMagon** [comment]
Yes, this is a new technical limitation of the current implementation, related to doing all the work through the helper. This can hardly be solved.
