### ISSUE TITLE
Confinement workaround patches for the KDiskMark snap

### ISSUE THREAD

**Issue by brlin-tw** [JonMagon/KDiskMark#90]
Hello, recently I found your [snap packaging implementation](https://github.com/JonMagon/KDiskMark-snap), try building it, and made some patches that will make it run and (with some limitations) run some tests on my storage device.  You may check out the patches at [my fork's branch](https://github.com/brlin-tw/KDiskMark-snap/tree/patch/workaround-confinement-issues).

Known issues:

* Settings > Flush pagecache option can't be enabled due to unavailable confinement interfaces that would properly enable so
* File > Save option will cause the application to hang
* Theme > Stylesheet Dark option doesn't have expected result

It may be possible to temporarily apply for classic confinement if the application can't be made into strict confinement due to snapd's own confinement interface limitations according to the [Process for reviewing classic confinement snaps](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460):

> #### Criteria
>
> This lists some criteria that might require classic (non-exhaustive):
>
> * access to resources not yet supported by snapd and where the requirement is clearly understood to be supportable by snapd. This may result in temporarily granting classic until snapd supports the use case in strict mode

Cheers!

**Comment by brlin-tw** [comment]
Closing as this is merely an informative notice that is not essentially related to this project.

**Comment by JonMagon** [comment]
Hello. Thanks for the investigation. I'll try your commits

**Comment by JonMagon** [comment]
Even as sudo, the application cannot write to protected directories. The snap restrictions are very strong, but I intend to bring the package back.
