### ISSUE TITLE
Theming functionality does not work

### ISSUE THREAD

**Issue by beucismis** [JonMagon/KDiskMark#91]
- Linux-distro: Devuan GNU/Linux Ceres (Linux 5.18.0-4)
- Desktop Environment: SwayWM on Wayland
- Qt Version:
- KDiskMark Version: 3.0.0
- FIO Version: fio-3.30

### Description:

Dark theme not working. Also my environment variables are:
```
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
```
I tried disabling qt5ct but it didn't work.

```
$ sudo ./kdiskmark.AppImage 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```

![2022-09-01T18:34:57,459814974+03:00](https://user-images.githubusercontent.com/40023234/187954240-04383bbc-3549-46f7-adc4-e25ea4e7ed01.png)

**Comment by beucismis** [comment]
I checked. Working properly. Thanks.

**Comment by PaulWentzel** [comment]
Hi there, on Ubuntu 24.04.1 LTS the same problem occours sadly.
