### ISSUE TITLE
ZFS mounts not listed and no option to add a dir in 3.0.0

### ISSUE THREAD

**Issue by Kadah** [JonMagon/KDiskMark#92]
- Linux-distro (kernel version): 5.15.0-46-generic #49~20.04.1-Ubuntu
- Desktop Environment (KDE/GNOME etc.): Xfce 4.14
- Qt Version: 5.12.9
- KDiskMark Version: 3.0.0
- FIO Version: fio-3.16

### Description:
In 3.0.0, no ZFS mount points are listed regardless of user write perms or running under sudo. This would be much of an issue, but the "add a directory" option is missing.

I have reverted back to 2.3.0 in the meantime.

### Steps To Reproduce:
Update from 2.3.0 to 3.0.0 from ppa.

**Comment by JonMagon** [comment]
It should list all mount points without having to add anything manually.
Could you please provide `cat /etc/mtab`?

**Comment by JonMagon** [comment]
Hm, I've never used that, as far as I understand, ZFS cannot be enumerated in the standard way. Then it makes sense to bring back the ability to manually specify the directory.

**Comment by Brandoskey** [comment]
The option to add a directory is still very much appreciated especially for testing NFS and SMB mounts, neither currently shows up automatically. I had to revert to 2.3.0

**Comment by JonMagon** [comment]
> The option to add a directory is still very much appreciated especially for testing NFS and SMB mounts, neither currently shows up automatically. I had to revert to 2.3.0

Thanks for the clarification. This has already been added to the master, will be in the next stable release.

**Comment by Kadah** [comment]
The only non-system mount points in mtab that showed in the list to select where a single ext4 drive and 2 vfat partitions used for boot. I have since removed that ext4 drive, so there isn't a whole lot to see now.

**rpool/ROOT/ubuntu_2tnbhv / zfs rw,relatime,xattr,posixacl 0 0**
/dev/nvme0n1p1 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
/dev/nvme0n1p1 /boot/grub vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
**DataPool /data zfs rw,relatime,xattr,posixacl 0 0**
